//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FotoAppDB.Migrations {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201703301740256_DB2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201703301740256_DB2() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FotoAppDB.Migrations.201703301740256_DB2", typeof(_201703301740256_DB2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu H4sIAAAAAAAEAN1c3W7juBW+L9B3EHTVFlkryWCBbWDvImNPiqCbZDr2LHo3YCTaESpRqkgFTos+2V70kfoKJSVRIkVSv7bsLHKT8OeQPOfj4TnUx/zv1//Of9qHgfUKE+xHaGFfzS5tCyI38ny0W9gp2X73g/3Tj7//3fyTF+6tX3i7D6wd7Ynwwn4hJL5xHOy+wBDgWei7SYSjLZm5UegAL3KuLy//7FxdOZCKsKksy5p/SRHxQ5j9Qf9cRsiFMUlB8BB5MMBFOa1ZZ1KtRxBCHAMXLuy7iES3cbz6aFu3gQ/oBNYw2NoWQCgigNDp3XzFcE2SCO3WMS0AweYthrTdFgQYFtO+qZp3XcHlNVuBU3XkotwUkyjsKfDqQ6ESp959kGLtUmVUaZ+ocskbW3WmuIVN9UuAS7Bt1Qe7WQYJayjodbb6mFlhxntdWGXdRQkBihT2c2Et04CkCVwgmJIEBBfW5/Q58N2/wrdN9A+IFigNAnF2dH60TiqgRZ+T [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
