// <auto-generated />
namespace FotoAppDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DB4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB4));
        
        string IMigrationMetadata.Id
        {
            get { return "201703312001560_DB4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
